plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
  - import
env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - eslint:recommended
  - plugin:jest/recommended
  - plugin:import/recommended
  - plugin:import/errors
  - plugin:import/warnings
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
  linebreak-style : 0,
  no-console: 'off',
  import/extensions: 'off' , # FIXME: remove when rule will be adjusted for new nodejs version
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
}
